# Inserts a blank line between shell prompts
add_newline = false

format = """$directory$character"""
right_format = """$all"""
# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
truncation_length = 2

[gradle]
format = "[$symbol($version )]($style)"

[java]
format = "[$symbol($version )]($style)"

[python]
format = "[$symbol($version )]($style)"

[golang]
format = "[$symbol($version )]($style)"

[c]
format = "[$symbol($version )]($style)"

[lua]
format = "[$symbol($version )]($style)"

[nodejs]
format = "[$symbol($version )]($style)"

[shell]
format = "[$symbol($version )]($style)"

[rust]
format = "[$symbol($version )]($style)"

[cmake]
format = "[$symbol($version )]($style)"
